### ISSUE TITLE
Sample external csv file

### ISSUE THREAD

**Issue by nilathj** [amacneil/cryptogains#16]
Hi, Can you please provide a sample external csv file.  I'm not really sure what the valid types are.  I just want to simulate a simple work flow, where I deposit some BTC, buy and sell an alt coin. I want to see the capital grain.

I tried to craft a csv file for this scenario, but I keep getting "ERROR: found 1 unreconciled transfers"

source,currency,date,type,amount,fee,exchangeCurrency,exchangeValue,usdValue
ledger,BTC,2017-01-01 00:00:00 UTC,transfer,0.3,0.00036547,,,
ledger,BTC,2017-01-01 00:00:00 UTC,send,-0.1,0.00046547,,,
ledger,BTC,2017-01-01 00:00:00 UTC,receive,0.1,0.00026547,,,

**Comment by amacneil** [comment]
See https://github.com/amacneil/cryptogains/blob/master/data/external.csv.example for an example.

You are getting the "unreconciled transfers" error because every "transfer" must have a matching transfer in another account. Transfer by definition means that it is between accounts that you own, so for safety we enforce that if you received a transfer of 0.3 BTC it must have been sent from somewhere.

Let me know if this is not clear or you need more explanation.

**Comment by nengine** [comment]
Hello, There are some BTC sales transactions, without 'BUY' transaction, but got as a result of selling altcoin like NEO/BTC.  Will it be able to also consider this type of transactions in calculating gains?  Thanks.

**Comment by amacneil** [comment]
@nengine yes, this is handled fine. I added some better examples to the csv, let me know if that's clear.

**Comment by nengine** [comment]
In the example below,  20000 XLM was initially bought for 0.2 BTC, in first two transactions.  And then sold those XLM for 2x and now accumulated 0.4 BTC.  Finally sell 0.4 BTC for USDT.  In this case should have gained 2000 but output is not showing anything.



```csv
source | currency | date | type | amount | fee | exchangeCurrency | exchangeValue | usdValue
ABCEX | XLM | 09/22/18 02:48 AM | buy | 10000 | 0 | BTC | 0.00001000 | -1000
ABCEX | XLM | 09/23/18 08:31 AM | buy | 10000 | 0 | BTC | 0.00001000 | -1000
ABCEX | XLM | 09/29/18 04:46 PM | sell | 20000 | 0 | BTC | 0.00002000 | 4000
ABCEX | BTC | 09/30/18 05:20 PM | sell | 0.4 | 0 | USDT | 10,000.00 | 4000
```


```
Importing external transactions
....
Reconciling transfers

Updating USD prices

Truncate gains

Calculating gains (BTC)

Calculating gains (NEO)

Summary:
.
 |
-|
'

Complete!
```

**Comment by amacneil** [comment]
The numbers in your `exchangeValue` column aren't right - you're saying 0.1 BTC (x2) but in the csv you have 0.00001 BTC. You then sold them for the exact same price (so no gain). Is that it?

**Comment by nengine** [comment]
Hello, Thanks.  I revised the numbers. 

1. Initially receive 0.2 BTC as a gift
2. Bought 20000 XLM  each 0.00001 BTC (20000 x 0.00001 = 0.2 BTC) for total of 0.2 BTC
3. Sold 20000 XLM each 0.00002 BTC (20000 x 0.00002 = 0.4 BTC) for total of 0.4 BTC
4. At this point 0.4 BTC accumulated ( initial 0.2 + 0.2 profit from XLM sale)
5. In the last transaction, when 0.4 BTC is sold, program output is saying that amountRemaining is 0.2, so it does not seem to accumulating extra BTC from profit of altcoin sales. 

```
source,currency,date,type,amount,fee,exchangeCurrency,exchangeValue,usdValue
ABCEX,BTC,2017-08-01 16:46:02.0000000 +00:00,receive,0.2,0,USDT,10000,2000
ABCEX,XLM,2017-08-22 02:48:23.0000000 +00:00,buy,10000,0,BTC,0.00001000,1000
ABCEX,XLM,2017-08-23 08:31:17.0000000 +00:00,buy,10000,0,BTC,0.00001000,1000
ABCEX,XLM,2017-08-28 16:46:02.0000000 +00:00,sell,-10000,0,BTC,0.00002000,2000
ABCEX,XLM,2017-08-28 16:47:02.0000000 +00:00,sell,-10000,0,BTC,0.00002000,2000
ABCEX,BTC,2017-08-28 16:48:02.0000000 +00:00,sell,-0.4,0,USDT,15000,6000
```

```js
transaction: { id: 6,
  accountId: 2,
  reference: null,
  order_id: null,
  trade_id: null,
  product_id: null,
  timestamp: 2017-08-28T16:48:02.000Z,
  amount: -0.4,
  currency: 'BTC',
  type: 'sell',
  exchangeReference: null,
  exchangeValue: 15000,
  exchangeCurrency: 'USDT',
  usdValue: 6000,
  usdPrice: 15000,
  transferTransactionId: null,
  source: 'file:ABCEX',
  sourceAmount: -0.4,
  sourceType: null,
  sourceAddress: null,
  sourceDescription: null,
  createdAt: 2019-03-31T11:05:19.758Z,
  updatedAt: 2019-03-31T11:05:19.758Z }
{ amountRemaining: '0.2' }
```

**Comment by amacneil** [comment]
A few notes:

* `exchangeValue` needs to be the total value, not the price per coin
* You don't need `exchangeCurrency` or `exchangeValue` if you received as a gift (it's only for buy/sell)
* The `usdValue` column is optional, we will look up USD price per bitcoin on that date if you don't fill it in. If you do use this column it should also be the total value and not the price per coin. But in your case I recommend to just leave it out.

So try this:

```
ABCEX,BTC,2017-08-01 16:46:02.0000000 +00:00,receive,0.2,0,,,
ABCEX,XLM,2017-08-22 02:48:23.0000000 +00:00,buy,10000,0,BTC,0.1,
ABCEX,XLM,2017-08-23 08:31:17.0000000 +00:00,buy,10000,0,BTC,0.1,
ABCEX,XLM,2017-08-28 16:46:02.0000000 +00:00,sell,-10000,0,BTC,0.2,
ABCEX,XLM,2017-08-28 16:47:02.0000000 +00:00,sell,-10000,0,BTC,0.2,
ABCEX,BTC,2017-08-28 16:48:02.0000000 +00:00,sell,-0.4,0,USD,6000,
```

**Comment by nengine** [comment]
Hello, I tired with new inputs like you suggested, but for some reason BTC accumulated as a result XLM sales does not seem to be added to the holds. Thanks.


```js
Calculating gains (BTC)
++
transaction: { id: 6,
  accountId: 1,
  reference: null,
  timestamp: 2017-08-28T16:48:02.000Z,
  amount: '-0.4',
  currency: 'BTC',
  type: 'sell',
  exchangeReference: null,
  exchangeValue: '6000',
  exchangeCurrency: 'USD',
  usdValue: '6000.00',
  usdPrice: '15000.00',
  transferTransactionId: null,
  source: 'file:ABCEX',
  sourceAmount: '-0.4',
  sourceType: null,
  sourceAddress: null,
  sourceDescription: null,
  createdAt: 2019-04-03T21:38:56.328Z,
  updatedAt: 2019-04-03T21:38:56.328Z }
{ amountRemaining: '0.2' }
Error: tried to dispose with no available holds: probably missing transactions.
    at calculateGainsForCurrency (/home/stellar/cryptogains/src/calculategains.js:268:17)
    at <anonymous>

```

**Comment by ryangrush** [comment]
```
source | currency | date | type | amount | fee | exchangeCurrency | exchangeValue | usdValue
ABCEX | XLM | 09/22/18 02:48 AM | buy | 10000 | 0 | BTC | 0.00001000 | -1000
ABCEX | XLM | 09/23/18 08:31 AM | buy | 10000 | 0 | BTC | 0.00001000 | -1000
ABCEX | XLM | 09/29/18 04:46 PM | sell | 20000 | 0 | BTC | 0.00002000 | 4000
ABCEX | BTC | 09/30/18 05:20 PM | sell | 0.4 | 0 | USDT | 10000.00 | 4000
```

forgive me if this is a dumb question but in the scenario you had listed above, what makes the first two transactions a buy and the third one a sell? They're both crypto. Is it that BTC is a common trading pair that later converts to realized gains in the fourth transaction?

I'm trying to determine how to populate my `external.csv` with some missing transactions and am trying to figure out how to label it.

**Comment by amacneil** [comment]
Oh, you're right. Cryptogains uses double entry accounting so you will need to add a corresponding "buy" for each "sell" (and vice versa) if you are doing crypto<>crypto trades with csv entry. This happens automatically for you if you import from coinbase/poloniex/etc.

If you are only trading directly for USD or other fiat currency then it's not necessary since only the crypto portion of the trade is taxable.
