### ISSUE TITLE
January 19 2018 - 2nd GDAX BCH Fork Distribution of 0.0000 amount

### ISSUE THREAD

**Issue by rconnelly** [amacneil/cryptogains#7]
I have a transaction with null transaction id on Jan 19, 2018 in GDAX. It looks similar to the fork distribution the month before. Did anyone else have this issue? I had to add a second "BCHForkFix" to remove this extra transaction to get the tool to work.

<img width="963" alt="screen shot 2018-03-15 at 9 31 33 pm" src="https://user-images.githubusercontent.com/865693/37499195-c442a670-2898-11e8-8d7a-8f9bcd228031.png">

Has anyone else seen this issue?

**Comment by amacneil** [comment]
Weird that it is 0 amount. We should probably just ignore any 0 transfers. Did you receive this in addition to a BCH distribution in December, or is this your only transfer?

@mihar any idea what would cause this?

**Comment by rconnelly** [comment]
Yes, I received this jan transfer in addition to the transfer in December.

**Comment by amacneil** [comment]
Closing this issue as I don't have any explanation for it and it didn't happen to me. If others have the same problem then I'll happily accept a PR to handle it.
